version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  catalogapi:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    container_name: catalogapi
    ports:
      - "5276:8080"
      - "5277:8081"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;User Id=sa;Password=StrongP@ssw0rd!;Database=DevDemo;TrustServerCertificate=True;"
    networks:
      - backend
 
  orderapi:
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    container_name: orderapi
    ports:
      - "5280:8080"
      - "5281:8081"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;User Id=sa;Password=StrongP@ssw0rd!;Database=Order;TrustServerCertificate=True;"
    networks:
      - backend

  basketapi:
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    container_name: basketapi
    ports:
      - "5278:8080"
      - "5279:8081"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;User Id=sa;Password=StrongP@ssw0rd!;Database=Basket;TrustServerCertificate=True;"
    networks:
      - backend

  distributedcache:
    image : redis

  messagebroker:
    image: rabbitmq:management
    networks:
      - backend


  discount-grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  sql_data:

networks:
  backend:
